version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - sdev2004-ca-website
    ports:
      - 443:443
      - 80:80

  sdev2004-ca-website:
    image: ernestdecina/sdev2004-ca-website
    build: 
      context: ./sdev2004-ca-website
    ports:
      - 5000
    deploy:
      mode: replicated
      replicas: 1